import type { Metadata } from "next";
import { CookiesProvider } from 'next-client-cookies/server';
import "./globals.css";


export const metadata: Metadata = {
  title: "Spotify Higher or Lower",
  description: "Generated by create next app",
};



export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html>
      <body>
          <CookiesProvider>
            {children}
          </CookiesProvider>
      </body>
    </html>

  );
}
